feat: added animation util
googlemaps/android-maps-utils pull request #1151
Opened 2023-01-23 16:52 UTC by kikoso

This PR adds an animation util that can be applied beyond just the clustering.

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Edit the title of this pull request with a [semantic commit prefix](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type) (e.g. "fix: "), which is necessary for automated release workflows to decide whether to generate a new release and what type it should be.
- [X] Will this cause breaking changes to existing Java or Kotlin integrations? If so, ensure the commit has a `BREAKING CHANGE` footer so when this change is integrated a major version update is triggered. See: https://www.conventionalcommits.org/en/v1.0.0/
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #777 🦕

2023-01-23 20:28 UTC, wangela requested changes
Thank you for writing this new utility. Please add example usage to the README, either in a new sample or modifying an existing sample.

2023-02-03 11:09 UTC, kikoso commented
> Thank you for writing this new utility. Please add example usage to the README, either in a new sample or modifying an existing sample.

It is added.

2023-02-09 05:53 UTC, wangela approved these changes

2023-02-09 06:16 UTC, wangela approved these changes

2023-02-09 06:34 UTC, merged