Remove unnecessary warnings (#1256)
googlemaps/android-maps-utils pull request #1257
Opened 2023-10-26 17:26 UTC by jenxwa

Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Edit the title of this pull request with a [semantic commit prefix](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type) (e.g. "fix: "), which is necessary for automated release workflows to decide whether to generate a new release and what type it should be.
- [ ] Will this cause breaking changes to existing Java or Kotlin integrations? If so, ensure the commit has a `BREAKING CHANGE` footer so when this change is integrated a major version update is triggered. See: https://www.conventionalcommits.org/en/v1.0.0/
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1256 🦕

2023-10-26 18:15 UTC, wangela commented
@jenxwa Thanks for cleaning up the demo app! Once you sign the CLA, we'll take a look.

2023-10-27 15:08 UTC, kikoso requested changes
Can you take a look at the comments, @jenxwa ? Thanks!

2023-11-09 13:48 UTC, Willkxxx commented
Who is this

On Thu, Nov 9, 2023, 6:23 AM Enrique López Mañas ***@***.***>
wrote:

> @jenxwa <https://github.com/jenxwa> , did you have the chance to check
> the comments and the CLA?
>
> Also, you need to follow the semantic PR convention.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/googlemaps/android-maps-utils/pull/1257#issuecomment-1803732612>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANTYN3IOPE2LFCLUUWE3PLLYDTDLNAVCNFSM6AAAAAA6RSKHYKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBTG4ZTENRRGI>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2026-08-04 23:10 UTC, dkhawk commented
Thank you for the PR. We are closing this as stale since the demo app has been refactored significantly and the requested changes/CLA check have been inactive. Please feel free to open a new PR against the current codebase if you notice any remaining warnings.

2026-08-04 23:10 UTC, closed without merging