chore: added header checker
googlemaps/android-maps-utils pull request #1285
Opened 2023-12-07 14:06 UTC by kikoso

This PR adds a new GitHub flow to check whether our files contain a copyright header.

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Edit the title of this pull request with a [semantic commit prefix](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type) (e.g. "fix: "), which is necessary for automated release workflows to decide whether to generate a new release and what type it should be.
- [ ] Will this cause breaking changes to existing Java or Kotlin integrations? If so, ensure the commit has a `BREAKING CHANGE` footer so when this change is integrated a major version update is triggered. See: https://www.conventionalcommits.org/en/v1.0.0/
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #1284 🦕

2023-12-09 06:47 UTC, wangela commented
Should we add .gradle files too?

2023-12-15 17:32 UTC, wangela commented
This should be merged as a `chore:`

2023-12-15 17:33 UTC, wangela requested changes
Add .gradle

2024-01-26 23:54 UTC, wangela requested changes

2024-01-26 23:54 UTC, wangela commented on .github/header-checker-lint.yml
The header-check check is failing https://github.com/googlemaps/android-maps-utils/pull/1285/checks?check_run_id=20320966664

`.github/header-checker-lint.yml` should have a copyright year of 2024

2024-01-26 23:55 UTC, wangela commented on .github/header-checker-lint.yml
Sorry this is my fault for taking so long to review!

2024-06-20 21:33 UTC, dkhawk approved these changes

2024-06-20 21:33 UTC, merged