chore: adjust NonHierarchicalViewBasedAlgorithm demo and doc
googlemaps/android-maps-utils pull request #893
Opened 2021-06-10 06:17 UTC by AndreasBoehm

Clarify that width and height should be passed as dp to NonHierarchicalViewBasedAlgorithm

The calculations used to determine the visible bounds rely on the width and height being passed in as dp. The demo of the algorithm uses pixels which results in markers being rendered outside of the visible screen.

Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)
- [ ] Will this cause breaking changes to existing Java or Kotlin integrations? If so, ensure the commit has a `BREAKING CHANGE` footer so when this change is integrated a major version update is triggered. See: https://www.conventionalcommits.org/en/v1.0.0/

Fixes #<issue_number_goes_here> 🦕

2021-06-10 06:19 UTC, AndreasBoehm commented
@googlebot I signed it!

2021-06-15 21:45 UTC, barbeau requested changes
@AndreasBoehm Good catch! Thanks for fixing this.

Two requests:
1. Could you also fix the variables passed to `updateViewSize()` in `ClusteringViewModelDemoActivity` to be dp instead of pixels?
2. Could you run the Gradle task `generateV3` to fix this issue in the `v3` demo app product flavor as well? This task will autogenerate the relevant `v3` code from the changes you already made to the `gms` variant here. Note that currently the `main` branch `v3` variant is already behind the `gms` variant with some whitespace and formatting changes - I've opened https://github.com/googlemaps/android-maps-utils/pull/896 to fix this.

2021-06-16 06:58 UTC, AndreasBoehm commented
> @AndreasBoehm Good catch! Thanks for fixing this.
> 
> Two requests:
> 
> 1. Could you also fix the variables passed to `updateViewSize()` in `ClusteringViewModelDemoActivity` to be dp instead of pixels?
> 2. Could you run the Gradle task `generateV3` to fix this issue in the `v3` demo app product flavor as well? This task will autogenerate the relevant `v3` code from the changes you already made to the `gms` variant here. Note that currently the `main` branch `v3` variant is already behind the `gms` variant with some whitespace and formatting changes - I've opened #896 to fix this.

Thanks for your review @barbeau.
Sorry it totally missed the usages of `updateViewSize()`. I pushed a new commit that fixes the variables and with updated `v3` code (excluded whitespace only changes)

2021-06-16 14:23 UTC, barbeau approved these changes
LGTM! Thanks @AndreasBoehm!

2021-06-16 14:28 UTC, merged